
version: '3.7'
services:
  pastec:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '4212:4212'
    restart: always
    volumes:
      - C:\Users\mafragias\opt\pastec-index:/pastec/build/pastec-index:rw
    command:
      - /bin/sh 
      - -c
      - |
        ./pastec -p 4212 -i /pastec/build/pastec-index/pharos.dat /pastec/data/visualWordsORB.dat
        #  pastec_load_indexes:
        #    build:
        # context: ./../pastec-index
        # dockerfile: ./Dockerfile
        # ports:
        # - '3000:3000'
