
version: '3.7'
services:
  pastec:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '4212:4212'
    restart: always
    volumes:
      - ./../pastec-index:/pastec/build/pastec-index:rw
    command:
      - /bin/sh 
      - -c
      - |
        ./pastec -p 4212 -i /pastec/build/pastec-index/pharos.dat /pastec/data/visualWordsORB.dat
