
version: '3.7'
services:
  pastec:
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - '4212:4212'
    restart: always
    volumes:
      - ~/pastec-index:/pastec/build/pastec-index:rw
    command:
    	- curl 
    	- -X 
    	- POST 
    	- -d 
	    - '{\"type\":\"LOAD\", \"index_path\":\"/pastec/build/pastec-index/pharos.dat\"}'
	    - http://127.0.0.1:4212/index/io
